//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneSProject.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneSProject.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghe thuyết minh.
        /// </summary>
        public static string Btn_Listen {
            get {
                return ResourceManager.GetString("Btn_Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin quán.
        /// </summary>
        public static string Detail_Title {
            get {
                return ResourceManager.GetString("Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quán ăn.
        /// </summary>
        public static string ListHeader {
            get {
                return ResourceManager.GetString("ListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét mã QR.
        /// </summary>
        public static string QRHeader {
            get {
                return ResourceManager.GetString("QRHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đưa mã QR vào khung.
        /// </summary>
        public static string QRInstruction {
            get {
                return ResourceManager.GetString("QRInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin ứng dụng.
        /// </summary>
        public static string Set_AppInfo {
            get {
                return ResourceManager.GetString("Set_AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chế độ tối.
        /// </summary>
        public static string Set_DarkMode {
            get {
                return ResourceManager.GetString("Set_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi ngôn ngữ.
        /// </summary>
        public static string Set_Language {
            get {
                return ResourceManager.GetString("Set_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POIs gần đây.
        /// </summary>
        public static string Set_RecentPOI {
            get {
                return ResourceManager.GetString("Set_RecentPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng.
        /// </summary>
        public static string TabList {
            get {
                return ResourceManager.GetString("TabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string TabMap {
            get {
                return ResourceManager.GetString("TabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét QR.
        /// </summary>
        public static string TabQR {
            get {
                return ResourceManager.GetString("TabQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chỉnh.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn để xem chi tiết.
        /// </summary>
        public static string TapToView {
            get {
                return ResourceManager.GetString("TapToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng ngài.
        /// </summary>
        public static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
    }
}
